from django.urls import path
from . import views


urlpatterns = [
    path('polysphere3D_doc/', views.polysphere3D_doc, name='polysphere3D_doc'),
    path('polysphere3D_AnimationObjectGroup_doc/', views.polysphere3D_AnimationObjectGroup_doc, name='polysphere3D_AnimationObjectGroup_doc'),
    path('polysphere3D_BooleanKeyframeTrack_doc/', views.polysphere3D_BooleanKeyframeTrack_doc,
         name='polysphere3D_BooleanKeyframeTrack_doc'),
    path('polysphere3D_CameraHelper_doc/', views.polysphere3D_CameraHelper_doc, name='polysphere3D_CameraHelper_doc'),
    path('polysphere3D_ColorKeyframeTrack_doc/', views.polysphere3D_ColorKeyframeTrack_doc,
         name='polysphere3D_ColorKeyframeTrack_doc'),
    path('polysphere3D_CompressedTextureLoader_doc/', views.polysphere3D_CompressedTextureLoader_doc,
         name='polysphere3D_CompressedTextureLoader_doc'),
    path('polysphere3D_ConvertSolutionFormat_doc/', views.polysphere3D_ConvertSolutionFormat_doc,
         name='polysphere3D_ConvertSolutionFormat_doc'),
    path('polysphere3D_CreateObjects_doc/', views.polysphere3D_CreateObjects_doc,
         name='polysphere3D_CreateObjects_doc'),
    path('polysphere3D_CubicInterpolant_doc/', views.polysphere3D_CubicInterpolant_doc,
         name='polysphere3D_CubicInterpolant_doc'),
    path('polysphere3D_Curve_doc/', views.polysphere3D_Curve_doc, name='polysphere3D_Curve_doc'),
    path('polysphere3D_Cylindrical_doc/', views.polysphere3D_Cylindrical_doc, name='polysphere3D_Cylindrical_doc'),
    path('polysphere3D_DataTextureLoader_doc/', views.polysphere3D_DataTextureLoader_doc,
         name='polysphere3D_DataTextureLoader_doc'),
    path('polysphere3D_DiscreteInterpolant_doc/', views.polysphere3D_DiscreteInterpolant_doc,
         name='polysphere3D_DiscreteInterpolant_doc'),
    path('polysphere3D_EventDispatcher_doc/', views.polysphere3D_EventDispatcher_doc,
         name='polysphere3D_EventDispatcher_doc'),
    path('polysphere3D_ExtrudeGeometry_doc/', views.polysphere3D_ExtrudeGeometry_doc,
         name='polysphere3D_ExtrudeGeometry_doc'),
    path('polysphere3D_GenerateProblemMatrix_doc/', views.polysphere3D_GenerateProblemMatrix_doc,
         name='polysphere3D_GenerateProblemMatrix_doc'),
    path('polysphere3D_global_doc/', views.polysphere3D_global_doc, name='polysphere3D_global_doc'),
    path('polysphere3D_Interpolant_doc/', views.polysphere3D_Interpolant_doc, name='polysphere3D_Interpolant_doc'),
    path('polysphere3D_module_exports_doc/', views.polysphere3D_module_exports_doc,
         name='polysphere3D_module_exports_doc'),
    path('polysphere3D_NumberKeyframeTrack_doc/', views.polysphere3D_NumberKeyframeTrack_doc,
         name='polysphere3D_NumberKeyframeTrack_doc'),
    path('polysphere3D_OrbitControl_doc/', views.polysphere3D_OrbitControl_doc, name='polysphere3D_OrbitControl_doc'),
    path('polysphere3D_OrbitControl_js_doc/', views.polysphere3D_OrbitControl_js_doc, name='polysphere3D_OrbitControl_js_doc'),
    path('polysphere3D_PMREMGenerator_doc/', views.polysphere3D_PMREMGenerator_doc, name='polysphere3D_PMREMGenerator_doc'),
    path('polysphere3D_Pyramid_doc/', views.polysphere3D_Pyramid_doc, name='polysphere3D_Pyramid_doc'),
    path('polysphere3D_pyramid_js_doc/', views.polysphere3D_pyramid_js_doc, name='polysphere3D_pyramid_js_doc'),
    path('polysphere3D_PyramidLayer_doc/', views.polysphere3D_PyramidLayer_doc, name='polysphere3D_PyramidLayer_doc'),
    path('polysphere3D_QuaternionKeyframeTrack_doc/', views.polysphere3D_QuaternionKeyframeTrack_doc, name='polysphere3D_QuaternionKeyframeTrack_doc'),
    path('polysphere3D_QuaternionLinearInterpolant_doc/', views.polysphere3D_QuaternionLinearInterpolant_doc, name='polysphere3D_QuaternionLinearInterpolant_doc'),
    path('polysphere3D_scene_doc/', views.polysphere3D_scene_doc, name='polysphere3D_scene_doc'),
    path('polysphere3D_scene_js_doc/', views.polysphere3D_scene_js_doc, name='polysphere3D_scene_js_doc'),
    path('polysphere3D_Shape3D_doc/', views.polysphere3D_Shape3D_doc, name='polysphere3D_Shape3D_doc'),
    path('polysphere3D_Shapes3D_js_doc/', views.polysphere3D_Shapes3D_js_doc, name='polysphere3D_Shapes3D_js_doc'),
    path('polysphere3D_sol_scene_js_doc/', views.polysphere3D_sol_scene_js_doc, name='polysphere3D_sol_scene_js_doc'),
    path('polysphere3D_Solver_js_doc/', views.polysphere3D_Solver_js_doc, name='polysphere3D_Solver_js_doc'),
    path('polysphere3D_Spherical_doc/', views.polysphere3D_Spherical_doc, name='polysphere3D_Spherical_doc'),
    path('polysphere3D_SphericalHarmonics3_doc/', views.polysphere3D_SphericalHarmonics3_doc, name='polysphere3D_SphericalHarmonics3_doc'),
    path('polysphere3D_StringKeyframeTrack_doc/', views.polysphere3D_StringKeyframeTrack_doc, name='polysphere3D_StringKeyframeTrack_doc'),
    path('polysphere3D_three_js_doc/', views.polysphere3D_three_js_doc, name='polysphere3D_three_js_doc'),
    path('polysphere3D_UI_js_doc/', views.polysphere3D_UI_js_doc, name='polysphere3D_UI_js_doc'),
    path('polysphere3D_VectorKeyframeTrack_doc/', views.polysphere3D_VectorKeyframeTrack_doc, name='polysphere3D_VectorKeyframeTrack_doc'),
    path('ui_template/', views.ui_template, name='ui_template'),
    path('', views.landing, name='landing'),
]