# Generated by Django 4.2.6 on 2023-11-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_id', models.CharField(max_length=2)),
                ('piece_shape', models.TextField()),
            ],
        ),
    ]
