# Generated by Django 4.2.6 on 2023-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polysphere_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlepiece',
            name='piece_id',
            field=models.CharField(max_length=1),
        ),
    ]
