# Generated by Django 4.2.6 on 2023-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanoodleProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_descriptions', models.TextField(help_text='JSON array of piece strings')),
                ('grid_width', models.IntegerField()),
                ('grid_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=1, unique=True)),
                ('grid', models.TextField(help_text="JSON array of strings representing the piece's shape")),
                ('image_path', models.CharField(max_length=100)),
                ('rotation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KanoodleSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_data', models.TextField(help_text='Formatted string of the solution')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='polysphere_app.kanoodleproblem')),
            ],
        ),
    ]
